apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
    spec:
      containerConcurrency: 80
      containers:
      - image: ${IMAGE}
        env:
        - name: APP_ENV
          value: 'PROD'
        - name: APP_PORT
          value: '8080'
        - name: PAYMENT_URL
          value: 'https://api.xendit.co'
        - name: XENDIT_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: xendit-webhook-token
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: gcp-project-id
        - name: QR_PAYMENT_TOPIC
          value: 'qr-payment'
          
  traffic:
  - percent: 100
    latestRevision: true
