---
swagger: "2.0"
info:
  title: "integration - OpenAPI"
  description:
    "This is the OpenAPI specification for tatangharyadi/integration (https://github.com/tatangharyadi/integration).\
    \ An `apiKey` will be needed for authorization"
  version: "1.0.0"
schemes:
  - "https"
security: []
tags:
  - name: "auth"
    description: "Auth"
  - name: "auth0"
    description: "Auth0"
  - name: "loyalty"
    description: "Loyalty"
  - name: "voucherify"
    description: "Voucherify"

paths:
  /hello/auth:
    get:
      tags:
        - "auth"
      summary: "Hello World"
      operationId: "helloAuth"
      x-google-backend:
        address: https://integration-auth-238488984298.asia-southeast2.run.app
        path_translation: CONSTANT_ADDRESS
      security:
        - api_key: []
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
            example: "Hello, World!"
  /hello/loyalty:
    get:
      tags:
        - "loyalty"
      summary: "Hello World"
      operationId: "helloLoyalty"
      x-google-backend:
        address: https://integration-loyalty-238488984298.asia-southeast2.run.app
        path_translation: CONSTANT_ADDRESS
      security:
        - api_key: []
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
            example: "Hello, World!"

  /auth0/gettoken:
    post:
      tags:
        - "auth0"
      summary: "generate a token"
      operationId: "generateToken"
      x-google-backend:
        address: https://integration-auth-238488984298.asia-southeast2.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "Client object"
          required: true
          schema:
            $ref: "#/definitions/Client"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Token"
        401:
          description: "Unauthorized"

  /voucherify/getcustomer/{customerId}:
    get:
      tags:
        - "voucherify"
      summary: "Get a customer"
      operationId: "getCustomer"
      x-google-backend:
        address: https://integration-loyalty-238488984298.asia-southeast2.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      produces:
        - "application/json"
      parameters:
        - name: "customerId"
          in: "path"
          description: "Id of customer to return"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Customer"
        404:
          description: "Customer not found"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  oauth2:
    authorizationUrl: "https://yummycorp.jp.auth0.com/"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://yummycorp.jp.auth0.com/"
    x-google-jwks_uri: "https://yummycorp.jp.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://yummyos.yummycorp.com/"

definitions:

  Client:
    type: "object"
    required:
      - "client_id"
      - "client_secret"
    properties:
      client_id:
        type: "string"
      client_secret:
        type: "string"
      audience:
        type: "string"
        example: "pos-api"
      grant_type:
        type: "string"
        example: "client_credentials"
  Token:
    type: "object"
    required:
      - "access_token"
    properties:
      access_token:
        type: "string"
      scope:
        type: "string"
        example: "read:customer"
      expires_in:
        type: "integer"
        format: "int32"
      token_type:
        type: "string"
        example: "Bearer"

  Customer:
    type: "object"
    required:
      - "customer_id"
    properties:
      customer_id:
        type: "string"
        example: "customer id"
      name:
        type: "string"
        example: "name"
      phone:
        type: "string"
        example: "phone"
      credit:
        $ref: "#/definitions/Credit"
  Credit:
    type: "object"
    properties:
      last_transaction_date:
        type: "string"
        format: "date-time"
      period:
        type: "string"
        example: "period"
      limit:
        type: "number"
        format: "float"
      current_total:
        type: "number"
        format: "float"
